#!/bin/sh
# Checkout a branch from the current branch
# in this format: rj/<dd-mm>/<branch-name>

if [ $# -eq 0 ]; then
  echo "Please give branch name"
  exit 1
fi

date=$(date '+%d-%b'|awk '{print tolower($0)}')
# TODO: Replace with your name initials
git checkout -b "rj/$date/$1"
