#!/bin/bash
# Set your Slack status as away

# Required Raycast parameters:
# @raycast.schemaVersion 1
# @raycast.title AFK
# @raycast.mode compact

# TODO: Replace the placeholder with your Slack API token
SLACK_API_TOKEN="<SLACK ACCESS TOKEN>"

# Set your Slack status
curl -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" \
-H "Content-Type: application/json; charset=utf-8" \
-d '{"profile": {"status_text":"","status_emoji":"","status_expiration": 0}}' \
https://api.slack.com/api/users.profile.set

# Make a call to the Slack API to set your presence to "away"
curl -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" \
-H "Content-type: application/json" --data '{"presence": "away"}' \
https://slack.com/api/users.setPresence
