#!/bin/bash
# Set Slack status to eating meal

# Required Raycast parameters:
# @raycast.schemaVersion 1
# @raycast.title Slack status to meal
# @raycast.mode compact

# TODO: Replace the placeholder with your Slack API token
SLACK_API_TOKEN="<SLACK ACCESS TOKEN>"

# Set your status text and emoji
#STATUS_TEXT='Meal time'
STATUS_EMOJI=':shallow_pan_of_food:'

# Set your Slack status
curl -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" \
-H "Content-Type: application/json; charset=utf-8" \
-d "{\"profile\": {\"status_text\":\"\",\"status_emoji\":\"$STATUS_EMOJI\",\"status_expiration\": 0}}" \
https://api.slack.com/api/users.profile.set

# Slack API call to set your presence to "away"
curl -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" \
-H "Content-type: application/json" --data '{"presence": "away"}' \
https://slack.com/api/users.setPresence
